=== artemijan/BattleCrab/dist/game/data/xsd/npcs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="parameters" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:choice minOccurs="1" maxOccurs="unbounded">
										<xs:element name="param">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="value" type="xs:string" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="skill">
											<xs:complexType>
												<xs:attribute name="name" type="xs:token" use="required" />
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="level" type="xs:positiveInteger" use="required" />
											</xs:complexType>
										</xs:element>
										<xs:element name="minions">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="npc" minOccurs="1" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="id" type="xs:positiveInteger" use="required" />
															<xs:attribute name="count" type="xs:positiveInteger" use="required" />
															<xs:attribute name="max" type="xs:positiveInteger" use="optional" />
															<xs:attribute name="respawnTime" type="xs:nonNegativeInteger" use="required" />
															<xs:attribute name="weightPoint" type="xs:integer" use="optional" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:token" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
							<xs:element name="race" type="xs:token" minOccurs="0" maxOccurs="1" />
							<xs:element name="sex" type="xs:token" minOccurs="0" maxOccurs="1" />
							<xs:element name="equipment" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="chest" type="xs:nonNegativeInteger" />
									<xs:attribute name="rhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="lhand" type="xs:nonNegativeInteger" />
									<xs:attribute name="weaponEnchant" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="acquire" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="exp" type="xs:decimal" />
									<xs:attribute name="sp" type="xs:decimal" />
									<xs:attribute name="raidPoints" type="xs:decimal" />
								</xs:complexType>
							</xs:element>
							<xs:element name="mpReward" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="value" type="xs:positiveInteger" />
									<xs:attribute name="type">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="DIFF" />
												<xs:enumeration value="PER" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="ticks" type="xs:positiveInteger" />
									<xs:attribute name="affects">
										<xs:simpleType>
											<xs:restriction base="xs:token">
												<xs:enumeration value="SOLO" />
												<xs:enumeration value="PARTY" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="stats" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="vitals" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="hp" type="xs:decimal" />
												<xs:attribute name="hpRegen" type="xs:decimal" />
												<xs:attribute name="mp" type="xs:decimal" />
												<xs:attribute name="mpRegen" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attack" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="random" type="xs:nonNegativeInteger" />
												<xs:attribute name="critical" type="xs:decimal" />
												<xs:attribute name="accuracy" type="xs:float" />
												<xs:attribute name="attackSpeed" type="xs:float" />
												<xs:attribute name="reuseDelay" type="xs:nonNegativeInteger" />
												<xs:attribute name="type" type="xs:token" />
												<xs:attribute name="range" type="xs:nonNegativeInteger" />
												<xs:attribute name="distance" type="xs:nonNegativeInteger" />
												<xs:attribute name="width" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="defence" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
												<xs:attribute name="evasion" type="xs:integer" />
												<xs:attribute name="shield" type="xs:nonNegativeInteger" />
												<xs:attribute name="shieldRate" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="abnormalResist" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="physical" type="xs:decimal" />
												<xs:attribute name="magical" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="attribute" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="attack" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="type" type="xs:token" />
															<xs:attribute name="value" type="xs:nonNegativeInteger" />
														</xs:complexType>
													</xs:element>
													<xs:element name="defence" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="fire" type="xs:integer" />
															<xs:attribute name="water" type="xs:integer" />
															<xs:attribute name="wind" type="xs:integer" />
															<xs:attribute name="earth" type="xs:integer" />
															<xs:attribute name="holy" type="xs:integer" />
															<xs:attribute name="dark" type="xs:integer" />
															<xs:attribute name="default" type="xs:integer" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="speed" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:all>
													<xs:element name="walk" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
													<xs:element name="run" minOccurs="0" maxOccurs="1">
														<xs:complexType>
															<xs:attribute name="ground" type="xs:decimal" />
															<xs:attribute name="swim" type="xs:decimal" />
															<xs:attribute name="fly" type="xs:decimal" />
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:complexType>
										</xs:element>
										<xs:element name="hitTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
									</xs:all>
									<xs:attribute name="str" type="xs:nonNegativeInteger" />
									<xs:attribute name="int" type="xs:nonNegativeInteger" />
									<xs:attribute name="dex" type="xs:nonNegativeInteger" />
									<xs:attribute name="wit" type="xs:nonNegativeInteger" />
									<xs:attribute name="con" type="xs:nonNegativeInteger" />
									<xs:attribute name="men" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="status" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="unique" type="xs:boolean" />
									<xs:attribute name="attackable" type="xs:boolean" />
									<xs:attribute name="talkable" type="xs:boolean" />
									<xs:attribute name="targetable" type="xs:boolean" />
									<xs:attribute name="undying" type="xs:boolean" />
									<xs:attribute name="showName" type="xs:boolean" />
									<xs:attribute name="randomWalk" type="xs:boolean" />
									<xs:attribute name="randomAnimation" type="xs:boolean" />
									<xs:attribute name="flying" type="xs:boolean" />
									<xs:attribute name="canMove" type="xs:boolean" />
									<xs:attribute name="noSleepMode" type="xs:boolean" />
									<xs:attribute name="passableDoor" type="xs:boolean" />
									<xs:attribute name="hasSummoner" type="xs:boolean" />
									<xs:attribute name="canBeSown" type="xs:boolean" />
									<xs:attribute name="isDeathPenalty" type="xs:boolean" />
									<xs:attribute name="fakePlayer" type="xs:boolean" />
									<xs:attribute name="fakePlayerTalkable" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="skillList" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="skill" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:nonNegativeInteger" use="required" />
												<xs:attribute name="level" type="xs:nonNegativeInteger" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="shots" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="soul" type="xs:nonNegativeInteger" />
									<xs:attribute name="spirit" type="xs:nonNegativeInteger" />
									<xs:attribute name="shotChance" type="xs:nonNegativeInteger" />
									<xs:attribute name="spiritChance" type="xs:nonNegativeInteger" />
								</xs:complexType>
							</xs:element>
							<xs:element name="corpseTime" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1" />
							<xs:element name="exCrtEffect" type="xs:boolean" minOccurs="0" maxOccurs="1" />
							<xs:element name="sNpcPropHpRate" type="xs:decimal" minOccurs="0" maxOccurs="1" />
							<xs:element name="ai" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="skill" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="minChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="maxChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="primaryId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="shortRangeChance" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeId" type="xs:nonNegativeInteger" />
												<xs:attribute name="longRangeChance" type="xs:nonNegativeInteger" />
											</xs:complexType>
										</xs:element>
										<xs:element name="clanList" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:choice minOccurs="1" maxOccurs="unbounded">
													<xs:element name="clan" type="xs:token" />
													<xs:element name="ignoreNpcId" type="xs:nonNegativeInteger" />
												</xs:choice>
											</xs:complexType>
										</xs:element>
									</xs:all>
									<xs:attribute name="type" type="xs:token" />
									<xs:attribute name="aggroRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="clanHelpRange" type="xs:nonNegativeInteger" />
									<xs:attribute name="isChaos" type="xs:boolean" />
									<xs:attribute name="isAggressive" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							<xs:element name="dropLists" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="drop" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:int" name="id" use="required"/>
																	<xs:attribute type="xs:long" name="min" use="required"/>
																	<xs:attribute type="xs:long" name="max" use="required"/>
																	<xs:attribute type="xs:double" name="chance" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="group" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:int" name="id" use="required"/>
																				<xs:attribute type="xs:long" name="min" use="required"/>
																				<xs:attribute type="xs:long" name="max" use="required"/>
																				<xs:attribute type="xs:double" name="chance" use="required"/>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute type="xs:double" name="chance" use="optional"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="spoil" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:int" name="id" use="optional"/>
																	<xs:attribute type="xs:long" name="min" use="optional"/>
																	<xs:attribute type="xs:long" name="max" use="optional"/>
																	<xs:attribute type="xs:double" name="chance" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="lucky" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:int" name="id" use="optional"/>
																	<xs:attribute type="xs:long" name="min" use="optional"/>
																	<xs:attribute type="xs:long" name="max" use="optional"/>
																	<xs:attribute type="xs:double" name="chance" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collision" minOccurs="1" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="radius" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
										<xs:element name="height" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:attribute name="normal" type="xs:decimal" />
												<xs:attribute name="grown" type="xs:decimal" />
											</xs:complexType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="displayId" type="xs:positiveInteger" />
						<xs:attribute name="level" type="xs:byte" />
						<xs:attribute name="type" type="xs:token" />
						<xs:attribute name="name" type="xs:string" />
						<xs:attribute name="usingServerSideName" type="xs:boolean" />
						<xs:attribute name="title" type="xs:string" />
						<xs:attribute name="usingServerSideTitle" type="xs:boolean" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== artemijan/BattleCrab/dist/game/data/stats/npcs/35300-35399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/npcs.xsd">
	<npc id="35300" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>MALE</sex>
		<equipment rhand="2499" /> <!-- rhand: Elven Long Sword -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="30" critical="4" accuracy="5" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
			<skill id="4410" level="18" /> <!-- Extremely Strong P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4416" level="22" /> <!-- Defending Army -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<sNpcPropHpRate>8</sNpcPropHpRate>
		<ai aggroRange="1000" clanHelpRange="1200" isAggressive="false">
			<clanList>
				<clan>DOOR</clan>
				<clan>INNADRILE_SIEGE</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="8" />
			<height normal="23.5" />
		</collision>
	</npc>
	<npc id="35301" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>MALE</sex>
		<equipment rhand="276" /> <!-- rhand: Elven Bow -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="10" critical="8" accuracy="0" attackSpeed="253" reuseDelay="1500" type="BOW" range="1100" distance="10" width="0" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
			<skill id="4410" level="18" /> <!-- Extremely Strong P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="9" /> <!-- Bows -->
			<skill id="4416" level="22" /> <!-- Defending Army -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<sNpcPropHpRate>8</sNpcPropHpRate>
		<ai aggroRange="1000" clanHelpRange="1200" isAggressive="false">
			<clanList>
				<clan>DOOR</clan>
				<clan>INNADRILE_SIEGE</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="8" />
			<height normal="23.5" />
		</collision>
	</npc>
	<npc id="35302" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>FEMALE</sex>
		<equipment rhand="16" /> <!-- rhand: Great Spear -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="30" critical="4" accuracy="0" attackSpeed="253" type="POLE" range="80" distance="80" width="120" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
			<skill id="4410" level="18" /> <!-- Extremely Strong P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="11" /> <!-- Spears -->
			<skill id="4416" level="22" /> <!-- Defending Army -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<sNpcPropHpRate>8</sNpcPropHpRate>
		<ai aggroRange="1000" clanHelpRange="1200" isAggressive="false">
			<clanList>
				<clan>DOOR</clan>
				<clan>INNADRILE_SIEGE</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="7" />
			<height normal="25" />
		</collision>
	</npc>
	<npc id="35303" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>FEMALE</sex>
		<equipment rhand="2" /> <!-- rhand: Long Sword -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="30" critical="4" accuracy="5" attackSpeed="253" type="SWORD" range="40" distance="80" width="120" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
			<skill id="4410" level="18" /> <!-- Extremely Strong P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="3" /> <!-- One-handed Sword -->
			<skill id="4416" level="22" /> <!-- Defending Army -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<sNpcPropHpRate>8</sNpcPropHpRate>
		<ai aggroRange="1000" clanHelpRange="1200" isAggressive="false">
			<clanList>
				<clan>DOOR</clan>
				<clan>INNADRILE_SIEGE</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="7" />
			<height normal="25" />
		</collision>
	</npc>
	<npc id="35304" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>FEMALE</sex>
		<equipment rhand="14" /> <!-- rhand: Bow -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="10" critical="8" accuracy="0" attackSpeed="253" reuseDelay="1500" type="BOW" range="1100" distance="10" width="0" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
			<skill id="4410" level="18" /> <!-- Extremely Strong P. Atk. -->
			<skill id="4411" level="11" /> <!-- Average M. Atk. -->
			<skill id="4412" level="11" /> <!-- Average P. Def. -->
			<skill id="4413" level="11" /> <!-- Average M. Def. -->
			<skill id="4414" level="2" /> <!-- Standard Type -->
			<skill id="4415" level="9" /> <!-- Bows -->
			<skill id="4416" level="22" /> <!-- Defending Army -->
		</skillList>
		<exCrtEffect>true</exCrtEffect>
		<sNpcPropHpRate>8</sNpcPropHpRate>
		<ai aggroRange="1000" clanHelpRange="1200" isAggressive="false">
			<clanList>
				<clan>DOOR</clan>
				<clan>INNADRILE_SIEGE</clan>
			</clanList>
		</ai>
		<collision>
			<radius normal="7" />
			<height normal="25" />
		</collision>
	</npc>
	<npc id="35305" level="75" type="Defender" name="Escort" title="Innadril">
		<!-- Confirmed CT2.5 -->
		<race>CASTLE_GUARD</race>
		<sex>MALE</sex>
		<equipment rhand="16" /> <!-- rhand: Great Spear -->
		<acquire exp="562" sp="1" />
		<stats str="40" int="21" dex="30" wit="20" con="43" men="20">
			<vitals hp="2676.65854" hpRegen="8.5" mp="1507.8" mpRegen="3" />
			<attack physical="794.70901" magical="542.68324" random="30" critical="4" accuracy="0" attackSpeed="253" type="POLE" range="80" distance="80" width="120" />
			<defence physical="319.24623" magical="233.61053" />
			<attribute>
				<defence fire="40" water="40" wind="40" earth="40" holy="40" dark="40" />
			</attribute>
			<speed>
				<walk ground="50" />
				<run ground="120" />
			</speed>
		</stats>
		<status undying="false" />
		<skillList>
			<skill id="4045" level="1" /> <!-- Resist Full Magic Attack -->
			<skill id="4408" level="16" /> <!-- HP Increase (8x) -->
			<skill id="4409" level="11" /> <!-- MP Increase (3x) -->
